import type { Metadata } from "next";
import { Nav, SiteFooter } from "@/components/home/sections";

export const metadata: Metadata = {
  title: "Terms of Service — VariationiQ",
  description: "The terms governing use of VariationiQ.",
};

export default function TermsPage() {
  return (
    <div className="relative min-h-screen bg-ip-bg font-ip text-ip-ink">
      <Nav />
      <main className="mx-auto max-w-[720px] px-6 py-20 sm:px-12 lg:px-16">
        <p className="ip-label text-ip-ink-3">Terms of Service</p>
        <h1 className="mt-2 text-3xl font-bold tracking-tight text-ip-ink">Terms of Service</h1>
        <p className="mt-2 text-[13px] text-ip-ink-3">Last updated: {new Date().getFullYear()}</p>

        <div className="mt-6 rounded-md border border-ip-orange/30 bg-ip-orange/12 px-4 py-3 text-[13px] leading-relaxed text-ip-ink-2">
          <strong className="text-ip-ink">Draft — pending legal review.</strong> These terms have not yet been
          reviewed by a lawyer. Don&apos;t treat this as a finalized, binding legal document until this notice is
          removed.
        </div>

        <div className="mt-8 space-y-6 text-[15px] leading-relaxed text-ip-ink-2">
          <section>
            <h2 className="text-lg font-semibold text-ip-ink">What VariationiQ does</h2>
            <p className="mt-2">
              VariationiQ analyzes project documents you upload and surfaces potential construction variations,
              with an estimated recoverable value and time-bar risk flag. Findings are AI-generated candidates —
              not legal advice, and not a guarantee of entitlement. A human on your team reviews and confirms each
              one before it should be relied on or submitted as a claim.
            </p>
          </section>
          <section>
            <h2 className="text-lg font-semibold text-ip-ink">Your responsibilities</h2>
            <p className="mt-2">
              You&apos;re responsible for the accuracy of the documents you upload and for verifying any variation
              before acting on it commercially or legally. Access to your organization&apos;s account is your
              responsibility to manage — admins can invite, remove, and set roles for team members.
            </p>
          </section>
          <section>
            <h2 className="text-lg font-semibold text-ip-ink">Availability</h2>
            <p className="mt-2">
              We aim for reliable uptime but don&apos;t guarantee uninterrupted service. We&apos;ll try to give
              notice of planned maintenance that could affect access.
            </p>
          </section>
          <section>
            <h2 className="text-lg font-semibold text-ip-ink">AI disclaimer</h2>
            <p className="mt-2">
              Variation candidates, value estimates, and time-bar risk flags produced by VariationiQ are generated
              by AI analysis of the documents you upload. They are <strong className="text-ip-ink">recommendations
              only</strong> — not legal advice, not a quantity surveyor&apos;s assessment, and not a determination
              of contractual entitlement. AI-generated output can be incomplete, wrong, or miss relevant context
              that isn&apos;t present in the uploaded documents. A qualified person on your team must review and
              confirm each variation before it is relied on, submitted as a claim, or used in any commercial or
              contractual decision. Do not treat unconfirmed (pending) variations as verified facts.
            </p>
          </section>
          <section>
            <h2 className="text-lg font-semibold text-ip-ink">Limitation of liability</h2>
            <p className="mt-2">
              VariationiQ is a tool that assists with identifying and organizing potential variations from your
              project documents — it does not guarantee that any variation will be accepted, that any claim will
              succeed, or that any amount will actually be recovered. To the maximum extent permitted by law, we
              are not liable for commercial or contractual outcomes arising from your organization&apos;s use of,
              or reliance on, output generated by VariationiQ, including AI-generated variation candidates,
              estimates, or risk flags. You remain responsible for independently verifying anything before acting
              on it.
            </p>
          </section>
          <section>
            <h2 className="text-lg font-semibold text-ip-ink">Intellectual property</h2>
            <p className="mt-2">
              You and your organization retain ownership of the documents, project data, and content you upload to
              VariationiQ. We claim no ownership over your project data and only use it to provide the service to
              you, as described in our{" "}
              <a href="/privacy" className="text-ip-navy underline">Privacy Policy</a>. VariationiQ, in turn,
              retains all ownership of the VariationiQ software, platform, and branding (including the VariationiQ
              name and logo) — nothing in these terms transfers any of that to you or your organization.
            </p>
          </section>
          <section>
            <h2 className="text-lg font-semibold text-ip-ink">Subscription &amp; billing</h2>
            <p className="mt-2">
              Current plans and pricing are published at <a href="/pricing" className="text-ip-navy underline">variationiq.com/pricing</a>.
              Paid subscriptions are billed monthly or annually in advance via Stripe, renew automatically until
              cancelled, and are presented to you for confirmation before you&apos;re charged. You can cancel or
              change your plan at any time from your organization&apos;s billing settings; cancellation takes effect
              at the end of the current billing period.
            </p>
          </section>
          <section>
            <h2 className="text-lg font-semibold text-ip-ink">Termination</h2>
            <p className="mt-2">
              You can close your organization&apos;s account at any time by contacting{" "}
              <a href="mailto:hello@variationiq.com" className="text-ip-navy underline">hello@variationiq.com</a>{" "}
              and requesting deletion — see <a href="/privacy" className="text-ip-navy underline">Data
              retention</a> above for what happens to your data afterwards. We may suspend or terminate an
              account that we reasonably believe is being used unlawfully, in a way that risks the security or
              availability of the service for other customers, or in material breach of these terms. Where
              practical, we&apos;ll try to give notice and an opportunity to resolve the issue before suspending
              an account.
            </p>
          </section>
          <section>
            <h2 className="text-lg font-semibold text-ip-ink">Governing law</h2>
            <p className="mt-2">
              These terms are intended to be governed by the laws of Australia. The specific state/territory
              jurisdiction is still to be confirmed and will be finalized as part of legal review — treat this
              section as a placeholder until then.
            </p>
          </section>
          <section>
            <h2 className="text-lg font-semibold text-ip-ink">Changes</h2>
            <p className="mt-2">
              We may update these terms as the product changes. Material changes will be communicated to account
              admins.
            </p>
          </section>
          <section>
            <h2 className="text-lg font-semibold text-ip-ink">Contact</h2>
            <p className="mt-2">
              Questions about these terms:{" "}
              <a href="mailto:hello@variationiq.com" className="text-ip-navy underline">hello@variationiq.com</a>.
            </p>
          </section>
        </div>
      </main>
      <SiteFooter />
    </div>
  );
}
